"""Co-Sight SkillFunction descriptor for the industrial report renderer."""

from app.agent_dispatcher.infrastructure.entity.SkillFunction import SkillFunction


def create_industrial_control_report_skill():
    """Return a Skill descriptor compatible with Co-Sight's actor skill catalog."""
    return {
        "skill_name": "create_industrial_control_report",
        "skill_type": "function",
        "display_name_zh": "工业控制系统规范报告生成",
        "display_name_en": "Industrial Control Report Output",
        "description_zh": (
            "根据工作区内已保存的 report_spec.json，确定性生成与控制系统课程报告风格一致的 "
            "HTML 预览、LaTeX 源码和可选 PDF。只在最终报告阶段调用；禁止直接让模型拼接 LaTeX。"
        ),
        "description_en": (
            "Deterministically render a validated report_spec.json from the workspace into a "
            "control-system style HTML report, LaTeX source, and optional PDF. Use only for the final report."
        ),
        "semantic_apis": ["api_report_generation", "api_file_management"],
        "function": SkillFunction(
            id="f7e2c4a1-6b9d-4f02-8a73-21d5e9c0b684",
            name=(
                "app.cosight.tool.industrial_report_toolkit."
                "IndustrialReportToolkit.render_report"
            ),
            description_zh=(
                "读取工作区内的 report_spec.json，生成 report.html、main.tex、manifest.json，"
                "并可在本机安装 XeLaTeX 时生成 report.pdf。"
            ),
            description_en=(
                "Read report_spec.json from the workspace and generate report.html, main.tex, "
                "manifest.json, and optionally report.pdf when XeLaTeX is installed."
            ),
            parameters={
                "type": "object",
                "properties": {
                    "report_spec_path": {
                        "type": "string",
                        "description_zh": "工作区内 report_spec.json 的相对或绝对路径",
                        "description_en": "Relative or absolute path to report_spec.json inside the workspace",
                    },
                    "output_dir": {
                        "type": "string",
                        "description_zh": "工作区内的输出目录，默认 report_output",
                        "description_en": "Output directory inside the workspace; defaults to report_output",
                        "default": "report_output",
                    },
                    "formats": {
                        "type": "array",
                        "items": {"type": "string", "enum": ["html", "latex"]},
                        "description_zh": "输出格式，可选 html、latex；默认两种都输出",
                        "description_en": "Output formats: html and/or latex; both are generated by default",
                    },
                    "compile_pdf": {
                        "type": "boolean",
                        "description_zh": "是否尝试使用本机 XeLaTeX 编译 PDF，默认 false",
                        "description_en": "Whether to try compiling a PDF with local XeLaTeX; defaults to false",
                        "default": False,
                    },
                },
                "required": ["report_spec_path"],
            },
        ),
    }
